(defun load-problems (path-to-file)
    (load-file path-to-file)
)

(defun load-file (path-to-file)
    (with-open-file (stream path-to-file)
        (loop for line = (read-line stream nil)
            while line
            collect (read-from-string line)
        )
    )
)

(defun display-board (board)
    (build-board (car board)(cadr board))
)

(defun build-board-horizontal-arc (line-list)
    (cond ((null line-list) ".")
          ((not (numberp (car line-list))) nil)
          ((= (car line-list) 0) (concatenate 'string ".    " (build-board-horizontal-arc (cdr line-list))))
          ((= (car line-list) 1) (concatenate 'string ".----" (build-board-horizontal-arc (cdr line-list))))
          (t nil)
    )
)

(defun build-board-vertical-arc (vertical-list)
     (cond ((null vertical-list) "")
          ((not (numberp (car vertical-list))) nil)
          ((= (car vertical-list) 0) (concatenate 'string "     " (build-board-vertical-arc (cdr vertical-list))))
          ((= (car vertical-list) 1) (concatenate 'string "|    " (build-board-vertical-arc (cdr vertical-list))))
          (t nil)
    )
)

(defun build-board (lines-list column-list)
    (let ((vertical-list (mapcar #'car column-list))
          (next-column-list (mapcar #'cdr column-list)))
        (cond ((null lines-list) "")
              ((null lines-list) (concatenate 'string (build-board-vertical-arc vertical-list) '(#\NewLine) (build-board lines-list next-column-list)))
              (t (concatenate 'string (build-board-horizontal-arc (car lines-list)) '(#\NewLine) (build-board-vertical-arc vertical-list) '(#\NewLine) (build-board (cdr lines-list) next-column-list)))
        )
    )
)

(defun output-results (solution algorithm)
    (let ((board (display-board (caar solution)))
        (runtime (float (* (car (last solution)) 0.000001)))
        (total-nodes (cadr solution))
        (expanded-nodes (caddr solution))
        (penetrance (cadddr solution))
        (branch-factor (cadr (reverse solution)))
        (path-to-sol (get-all-states (car solution)))
        )
        (with-open-file (out "results.txt" :direction :output :if-exists :append :if-does-not-exist :create)
            (format out "Board: ~%~a~%" board)
            (format out "Number of generated nodes: ~a~%" total-nodes)
            (format out "Number of expanded nodes: ~a~%" expanded-nodes)
            (format out "Algorithm used: ~a~%" algorithm)
            (format out "Run time: ~fms~%" runtime)
            (format out "Penetrance: ~f~%" penetrance)
            (format out "Effective branching factor: ~f~%" branch-factor)
            (format out "Path to solution: ~a~%" path-to-sol)
            (format out "--------------------------------------------------------------------------------------~%")
        )
    )
)

(defun print-results (solution algorithm)
    (let ((board (display-board (caar solution)))
        (runtime (float (* (car (last solution)) 0.000001)))
        (total-nodes (cadr solution))
        (expanded-nodes (caddr solution))
        (penetrance (cadddr solution))
        (branch-factor (cadr (reverse solution)))
        (path-to-sol (get-all-states (car solution)))
        )
        (format t "Board: ~%~a~%" board)
        (format t "Number of generated nodes: ~a~%" total-nodes)
        (format t "Number of expanded nodes: ~a~%" expanded-nodes)
        (format t "Algorithm used: ~a~%" algorithm)
        (format t "Run time: ~fms~%" runtime)
        (format t "Penetrance: ~f~%" penetrance)
        (format t "Effective branching factor: ~f~%" branch-factor)
        (format t "Path to solution: ~a~%" path-to-sol)
        (output-results solution algorithm)
    )
)

(defun main-menu ()
    (format t "~%~%~%~%~%~%~%~%~%")
    (format t "Welcome to the Dots and Boxes problem solving project!~%")
    (format t "Developed by: Andre Dias and Joao Caetano~%~%")
    (problem-menu)
)

(defun problem-menu ()
    (let ((problems-list (load-problems "problemas.dat")))
       (format t "Choose the problem to solve: ~%")
       (show-problems problems-list)
       (let ((inp (read)))
            (if (or (not (numberp inp)) (> inp (length problems-list)) (< inp 1))
                (problem-menu)
                (let ((problem (nth (- inp 1) problems-list)))
                    (algorithm-menu problem)
                )
            )
        )
    ) 
)

(defun depth-menu (problem algorithm)
    (format t "Pick the maximum tree depth (bigger than 0): ")
    (let ((inp (read)))
        (if (or (not (numberp inp)) (< inp 0))
            (depth-menu problem algorithm)
            (run-search problem algorithm)
        )
    )
)

(defun heuristic-menu (problem algorithm)
    (format t "Pick a search heuristic:~%1.Enunacido o(x) - c(x)~%2.Projeto (o(x)-c(x)/a(x))~%~%o(x) = Objetivo caixas fechadas~%c(x) = Caixas fechadas~%a(x) = Tipo de arcos adjacentes~%")
    (let ((inp (read)))
        (if (or (not (numberp inp)) (> inp 2) (< inp 1))
            (heuristic-menu problem algorithm)
            (ecase inp
                (1 (run-search problem algorithm 0 'h1))
                (2 (run-search problem algorithm 0 'h2))
            )
        )    
    )
)

(defun algorithm-menu (problem)
    (format t "Choose the searching algorithm:~%~%1.BFS~%2.DFS~%3.A*~%")
    (let ((inp (read)))
        (if (or (not (numberp inp)) (> inp 3) (< inp 1))
            (algorithm-menu problem)
            (ecase inp
                (1 (run-search problem 'bfs))
                (2 (depth-menu problem 'dfs))
                (3 (heuristic-menu problem 'a*))
            )
        )    
    )
)

(defun run-search (problem algorithm &optional depth h-func)
    (format t "~%Calculating...~%")
    (ecase algorithm
        ('bfs (print-results (funcall algorithm (list (create-node (car problem))) nil (cadr problem)) algorithm))
        ('dfs (print-results (funcall algorithm (list (create-node (car problem))) nil (cadr problem) depth) algorithm))
        ('a* (print-results (funcall algorithm (list (create-node (car problem))) nil (cadr problem) h-func) algorithm))
    )
)

(defun show-problems (problems &optional (i 1))
    (cond ((null problems) (format t ""))
          (t (let ((problem (car problems)))
            (format t "~a. Board: ~%~a~%" i (display-board (car problem)))
            (show-problems (cdr problems) (1+ i))))
    )
)

(defun load-lisp-files ()
    (load (compile-file "puzzle.lisp"))
    (load (compile-file "procura.lisp"))
    (load (compile-file "projeto.lisp"))
)

(defun start ()
    (load-lisp-files)
    (main-menu)
)
